import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [display, setDisplay] = useState(false);

  const [formData, setFormData] = useState({
    name: "",
    speaker: "",
    date: "",
    time: "",
    detail: "",
  });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    setDisplay(false);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setFormData({ ...formData });
    setDisplay(true);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>event meetup banner</h1>
        <div className="run">
          <div className="details">
            <div className="label">
              <label>event name</label>
              <input
                type="text"
                placeholder="name"
                name="name"
                value={formData.name}
                onChange={handleChange}
              />
            </div>
            <div className="label">
              <label>event speakers</label>
              <input
                type="text"
                placeholder="speaker"
                name="speaker"
                value={formData.speaker}
                onChange={handleChange}
              />
            </div>
            <div className="label">
              <label>date</label>
              <input
                type="text"
                name="date"
                value={formData.date}
                onChange={handleChange}
              />
            </div>
            <div className="label">
              <label>time</label>
              <input
                type="number"
                name="time"
                value={formData.time}
                onChange={handleChange}
              />
            </div>
            <div className="label">
              <label>Venue</label>
              <textarea
                className="textarea"
                type="text"
                name="detail"
                placeholder="type here"
                value={formData.detail}
                onChange={handleChange}
              />
              <button onClick={handleSubmit}>Generate Banner</button>
            </div>
          </div>
          <div className="bad">
            <img
              src="https://res.cloudinary.com/ugwutotheeshoes/image/upload/c_scale,h_450,w_750/v1649721585/pawel-czerwinski-dgJT71cXlC4-unsplash_usrnmt.jpg"
              alt="event image"
            />
            <div className="view">
              <h1>{display ? formData.name : ""}</h1>
              <h3>{display ? `speaker: ${formData.speaker}` : ""}</h3>
              <p> {display ? `date: ${formData.date}` : ""}</p>
              <p> {display ? `time: ${formData.time}pm` : ""}</p>
              <p>{display ? `venue: ${formData.detail}` : ""}</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
